### ISSUE TITLE
Unable to run scheduled task with different user than transport one

### ISSUE THREAD

**Issue by Annih** [smurawski/chef-zero-scheduled-task#14]
Hello @smurawski 

Nice provisioner, it solves most of my issues :+1: , but when I tried to run as SYSTEM to have a similar behavior as my production environment I encountered a small issue:
> WARN: *****************************************
> WARN: Did not find config file: C:\Windows\TEMP\kitchen\client.rb, using command line options.
> WARN: *****************************************

The scheduled task is looking for `client.rb` in temp folder, but this folder vary according to current user.
So the `client.rb` created with user vagrant, does not exist in my SYSTEM temp folder :(

This issue is not high priority at all for me and could be considered as an enhancement.

Thanks again for this gem!

cc: @aboten

**Comment by smurawski** [comment]
Closed by #17

**Comment by Annih** [comment]
4a4f1f2dfd052d6f90be992c10282d385451ac73 introduced a regression related to this issue.
