### ISSUE TITLE
Malformed chef-client-script.ps1 on test node

### ISSUE THREAD

**Issue by dcrosby** [smurawski/chef-zero-scheduled-task#23]
Test Node: Windows Server 2012 R2
Kitchen: 1.5.0
Hyper-V

Running kitchen converge stops on:
"SUCCESS: Atempted to run the scheduled task "chef-tk".
Checking the chef-client-script.ps1 that it's trying to run, the script is truncated:

`Add-Type -AssemblyName System.Core
start-sleep -seconds 5;
$npipeClient = new-object System.IO.Pipes.NamedPipeClientStream($env:ComputerName,
  'task', [System.IO.Pipes.PipeDirection]::Out);
$npipeclient.connect();
$pipeWriter = new-object System.IO.StreamWriter($npipeClient);
$pipeWriter.AutoFlush = $true;
& C:\opscode\chef\bin\chef-client.bat --local-mode --config C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\client.rb --log_level info --force-formatter --no-color --json-attributes C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\dna.json --chef-zero-port 8889 |
  foreach-object {} {$pipewriter.writeline($_)} {
    $pipewriter.writeline("`

The converge never completes.

**Comment by mwrock** [comment]
Assuming you may have gotten version 0.0.11? This bug should have been fixed in 0.0.12.

**Comment by dcrosby** [comment]
Worked like a gem! Thanks for the tip!
